package org.cine.dao.impl;
import org.cine.dao.MovimientoInventarioDAO;import org.cine.model.MovimientoInventario;import org.cine.util.Conexion;import java.sql.*;import java.util.*;
public class MovimientoInventarioDAOImpl implements MovimientoInventarioDAO {
public void registrar(int producto,int usuario,String tipo,int cantidad,String observacion)throws SQLException {
if(!tipo.equals("ENTRADA")&&!tipo.equals("SALIDA"))throw new SQLException("Tipo de movimiento inválido.");if(cantidad<=0)throw new SQLException("La cantidad debe ser positiva.");
try(Connection c=Conexion.getInstance().getConnection()){c.setAutoCommit(false);try{int stock;try(PreparedStatement s=c.prepareStatement("SELECT stock FROM productos WHERE id_producto=? FOR UPDATE")){s.setInt(1,producto);try(ResultSet r=s.executeQuery()){if(!r.next())throw new SQLException("Producto no encontrado.");stock=r.getInt(1);}}if(tipo.equals("SALIDA")&&stock<cantidad)throw new SQLException("Stock insuficiente.");try(PreparedStatement s=c.prepareStatement("UPDATE productos SET stock=stock+? WHERE id_producto=?")){s.setInt(1,tipo.equals("ENTRADA")?cantidad:-cantidad);s.setInt(2,producto);s.executeUpdate();}try(PreparedStatement s=c.prepareStatement("INSERT INTO movimientos_inventario(id_producto,id_usuario,tipo_movimiento,cantidad,observacion) VALUES(?,?,?,?,?)")){s.setInt(1,producto);s.setInt(2,usuario);s.setString(3,tipo);s.setInt(4,cantidad);s.setString(5,observacion);s.executeUpdate();}c.commit();}catch(Exception e){c.rollback();if(e instanceof SQLException sql)throw sql;throw new SQLException(e);}finally{c.setAutoCommit(true);}}
}
public List<MovimientoInventario> listar()throws SQLException{List<MovimientoInventario> out=new ArrayList<>();String sql="SELECT m.*,p.nombre_producto,CONCAT(u.nombre_usuario,' ',u.apellido_usuario) AS operador FROM movimientos_inventario m JOIN productos p ON p.id_producto=m.id_producto JOIN usuarios u ON u.id_usuario=m.id_usuario ORDER BY m.fecha_movimiento DESC,m.id_movimiento DESC";try(Connection c=Conexion.getInstance().getConnection();PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){while(r.next())out.add(new MovimientoInventario(r.getInt("id_movimiento"),r.getInt("id_producto"),r.getInt("id_usuario"),r.getString("nombre_producto"),r.getString("operador"),r.getString("tipo_movimiento"),r.getInt("cantidad"),r.getTimestamp("fecha_movimiento").toLocalDateTime(),r.getString("observacion")));}return out;}
}
