package org.cine.dao.impl;
import java.sql.*;import java.util.*;import org.cine.dao.VentaDAO;import org.cine.model.*;import org.cine.util.Conexion;
public class VentaDAOImpl implements VentaDAO {
 private Connection con() throws SQLException{return Conexion.getInstance().getConnection();}
 public List<Opcion> clientes() throws SQLException {List<Opcion> l=new ArrayList<>();try(Connection c=con();CallableStatement s=c.prepareCall("{call sp_listarclientesactivos()}");ResultSet rs=s.executeQuery()){while(rs.next())l.add(new Opcion(rs.getInt("id_cliente"),rs.getString("nombre_cliente")+" "+rs.getString("apellido_cliente")));}return l;}
 public List<Funcion> funciones() throws SQLException {List<Funcion> l=new ArrayList<>();String q="SELECT f.id_funcion,p.titulo,s.nombre_sala,f.fecha_inicio,f.precio_boleto FROM funciones f JOIN peliculas p ON p.id_pelicula=f.id_pelicula JOIN salas s ON s.id_sala=f.id_sala WHERE f.estado='programada' AND f.fecha_inicio>NOW() AND p.estado=1 AND s.estado=1 ORDER BY f.fecha_inicio";try(Connection c=con();PreparedStatement s=c.prepareStatement(q);ResultSet rs=s.executeQuery()){while(rs.next())l.add(new Funcion(rs.getInt(1),rs.getString(2)+" / "+rs.getString(3)+" / "+rs.getTimestamp(4),rs.getBigDecimal(5)));}return l;}
 public List<Butaca> butacas(int f) throws SQLException {List<Butaca> l=new ArrayList<>();try(Connection c=con();CallableStatement s=c.prepareCall("{call sp_listarbutacasfuncion(?)}")){s.setInt(1,f);try(ResultSet rs=s.executeQuery()){while(rs.next())l.add(new Butaca(rs.getInt("id_butaca"),rs.getString("fila")+rs.getInt("numero"),"disponible".equals(rs.getString("disponibilidad"))));}}return l;}
 private int id(String call,int... args) throws SQLException{try(Connection c=con();CallableStatement s=c.prepareCall(call)){for(int i=0;i<args.length;i++)s.setInt(i+1,args[i]);try(ResultSet rs=s.executeQuery()){if(rs.next())return rs.getInt(1);}throw new SQLException("No devolvió ID");}}
 private void ejecutar(String call,int... args) throws SQLException{try(Connection c=con();CallableStatement s=c.prepareCall(call)){for(int i=0;i<args.length;i++)s.setInt(i+1,args[i]);s.execute();}}
 public int abrir(int cliente,int usuario) throws SQLException{return id("{call sp_abrirventa(?,?)}",cliente,usuario);}
 public void agregar(int venta,int funcion,int butaca) throws SQLException{id("{call sp_agregarboleto(?,?,?)}",venta,funcion,butaca);}
 public void quitar(int venta,int boleto) throws SQLException{ejecutar("{call sp_quitarboleto(?,?)}",venta,boleto);}
 public void cancelar(int venta) throws SQLException{ejecutar("{call sp_eliminarventaabierta(?)}",venta);}
 public List<Boleto> boletos(int venta) throws SQLException{List<Boleto> l=new ArrayList<>();try(Connection c=con();CallableStatement s=c.prepareCall("{call sp_listarboletosventa(?)}")){s.setInt(1,venta);try(ResultSet rs=s.executeQuery()){while(rs.next())l.add(new Boleto(rs.getInt("id_boleto"),rs.getInt("id_butaca"),rs.getString("butaca"),rs.getBigDecimal("precio_unitario")));}}return l;}
 private Venta map(ResultSet rs)throws SQLException{return new Venta(rs.getInt("id_venta"),rs.getString("cliente"),rs.getString("estado"),rs.getBigDecimal("total_venta"));}
 public Venta confirmar(int venta)throws SQLException{try(Connection c=con();CallableStatement s=c.prepareCall("{call sp_confirmarventa(?)}")){s.setInt(1,venta);try(ResultSet rs=s.executeQuery()){if(rs.next())return map(rs);}}throw new SQLException("Venta no confirmada");}
 public Venta consultar(int venta)throws SQLException{try(Connection c=con();CallableStatement s=c.prepareCall("{call sp_buscarventa(?)}")){s.setInt(1,venta);try(ResultSet rs=s.executeQuery()){if(rs.next())return map(rs);}}throw new SQLException("Venta no encontrada");}
 public List<Venta> ventas()throws SQLException{List<Venta> l=new ArrayList<>();try(Connection c=con();CallableStatement s=c.prepareCall("{call sp_listarventas()}");ResultSet rs=s.executeQuery()){while(rs.next())l.add(map(rs));}return l;}
 public List<String> factura(int venta)throws SQLException{List<String> l=new ArrayList<>();try(Connection c=con();CallableStatement s=c.prepareCall("{call sp_verfactura(?)}")){s.setInt(1,venta);try(ResultSet rs=s.executeQuery()){while(rs.next())l.add(rs.getString("descripcion")+" | "+rs.getInt("cantidad")+" x Q"+rs.getBigDecimal("precio_unitario")+" = Q"+rs.getBigDecimal("subtotal"));}}return l;}
}
