package org.cine.controller;
import java.io.IOException;import javafx.fxml.FXML;import javafx.beans.property.SimpleStringProperty;import javafx.collections.FXCollections;import javafx.scene.control.*;import org.cine.model.CategoriaProducto;import org.cine.dao.impl.CategoriaProductoDAOImpl;import org.cine.system.Principal;
public class CategoriasProductoController {@FXML private TableView<CategoriaProducto> tabla;@FXML private TableColumn<CategoriaProducto,String> colNombre,colDescripcion,colEstado;@FXML private TextField nombre,descripcion;@FXML private Label mensaje;private CategoriaProducto seleccionada;private final CategoriaProductoDAOImpl dao=new CategoriaProductoDAOImpl();
@FXML private void initialize(){colNombre.setCellValueFactory(c->new SimpleStringProperty(c.getValue().nombre()));colDescripcion.setCellValueFactory(c->new SimpleStringProperty(c.getValue().descripcion()));colEstado.setCellValueFactory(c->new SimpleStringProperty(c.getValue().activo()?"Activo":"Inactivo"));tabla.getSelectionModel().selectedItemProperty().addListener((o,a,b)->{seleccionada=b;if(b!=null){nombre.setText(b.nombre());descripcion.setText(b.descripcion());}});recargar();}
@FXML private void recargar(){try{tabla.setItems(FXCollections.observableArrayList(dao.listar()));mensaje.setText("Categorías actualizadas.");}catch(Exception e){mensaje.setText("Error: "+e.getMessage());}}
@FXML private void nuevo(){seleccionada=null;tabla.getSelectionModel().clearSelection();nombre.clear();descripcion.clear();}
@FXML private void guardar(){try{if(nombre.getText().isBlank())throw new IllegalArgumentException("Escribe un nombre.");dao.guardar(seleccionada==null?null:seleccionada.id(),nombre.getText(),descripcion.getText());nuevo();recargar();mensaje.setText("Categoría guardada.");}catch(Exception e){mensaje.setText("Error: "+e.getMessage());}}
@FXML private void estado(){try{if(seleccionada==null)throw new IllegalArgumentException("Selecciona una categoría.");dao.cambiarEstado(seleccionada.id(),!seleccionada.activo());nuevo();recargar();}catch(Exception e){mensaje.setText("Error: "+e.getMessage());}}
@FXML private void eliminar(){try{if(seleccionada==null)throw new IllegalArgumentException("Selecciona una categoría.");dao.eliminar(seleccionada.id());nuevo();recargar();}catch(Exception e){mensaje.setText("No se puede eliminar una categoría con productos asociados: "+e.getMessage());}}
@FXML private void volver()throws IOException{Principal.mostrarConfiteria();}}
