package org.cine.controller;
import java.io.IOException;import javafx.fxml.FXML;import javafx.beans.property.SimpleStringProperty;import javafx.collections.FXCollections;import javafx.scene.control.*;import org.cine.model.*;import org.cine.dao.impl.*;import org.cine.service.SesionContext;import org.cine.system.Principal;
public class InventarioController {
@FXML private ComboBox<Producto> productos;@FXML private TextField cantidad,observacion;@FXML private ComboBox<String> tipo;@FXML private Label mensaje;@FXML private TableView<MovimientoInventario> tabla;@FXML private TableColumn<MovimientoInventario,String> colProducto,colTipo,colCantidad,colFecha,colUsuario,colObservacion;
private final ProductoDAOImpl pdao=new ProductoDAOImpl();private final MovimientoInventarioDAOImpl dao=new MovimientoInventarioDAOImpl();
@FXML private void initialize(){productos.setConverter(new javafx.util.StringConverter<>(){public String toString(Producto p){return p==null?"":p.nombre()+" ("+p.stock()+" disponibles)";}public Producto fromString(String s){return null;}});tipo.setItems(FXCollections.observableArrayList("ENTRADA","SALIDA"));tipo.setValue("ENTRADA");colProducto.setCellValueFactory(c->new SimpleStringProperty(c.getValue().nombreProducto()));colTipo.setCellValueFactory(c->new SimpleStringProperty(c.getValue().tipo()));colCantidad.setCellValueFactory(c->new SimpleStringProperty(""+c.getValue().cantidad()));colFecha.setCellValueFactory(c->new SimpleStringProperty(c.getValue().fecha().toString().replace('T',' ')));colUsuario.setCellValueFactory(c->new SimpleStringProperty(c.getValue().nombreUsuario()));colObservacion.setCellValueFactory(c->new SimpleStringProperty(c.getValue().observacion()));actualizar();}
@FXML private void actualizar(){try{productos.setItems(FXCollections.observableArrayList(pdao.listar()));tabla.setItems(FXCollections.observableArrayList(dao.listar()));mensaje.setText("Historial actualizado.");}catch(Exception e){mensaje.setText("Error: "+e.getMessage());}}
@FXML private void registrar(){try{Producto p=productos.getValue();if(p==null)throw new IllegalArgumentException("Selecciona un producto.");int q=Integer.parseInt(cantidad.getText().trim());var u=SesionContext.getUsuarioActual();if(u==null)throw new IllegalStateException("Sesión expirada.");String rol=u.getNombreRol();if(!"admin".equalsIgnoreCase(rol))throw new IllegalStateException("Solo administración puede registrar movimientos.");dao.registrar(p.id(),u.getIdUsuario(),tipo.getValue(),q,observacion.getText());actualizar();cantidad.clear();mensaje.setText("Movimiento registrado correctamente.");}catch(Exception e){mensaje.setText("Error: "+e.getMessage());}}
@FXML private void volver()throws IOException{Principal.mostrarDashboardSegunRol();}
}
